### ISSUE TITLE
Category and Attribute creation on the fly

### ISSUE THREAD

**Issue by ha0rex** [techdivision/import#146]
During the product import process, Magento's default importer creates categories if they don't exist, that is very handy. Have this functionality in a later release of M2IF would be cool.

The same on-the-fly creation of custom product attributes would be an extra, but also really helpful solution.

**Comment by wagnert** [comment]
Hi @ha0rex thanks for requesting that feature. With Custom Product Attributes you mean [Customizable Options](https://docs.magento.com/m2/ce/user_guide/catalog/settings-advanced-custom-options.html), not [Dynamic Option Creation](https://docs.m2if.com/getting-started/configuration#dynamic-option-creation), right?

**Comment by ha0rex** [comment]
Hi @wagnert thanks for coming back. I meant Attributes: https://stackoverflow.com/questions/4870332/magento-custom-options-vs-attributes

I have a huge csv (~250k products), with a lot of varied attributes in the additional_attributes fields (like color, jet_size, finish, etc.). When I import this with the Magento importer, it doesn't create the attribute if it's not exist yet, moreover I have to add them manually to a product first, make an export (not sure if this step is indispensable), to be able to import them.

Creating these attributes on the fly during the product import process would be great, then I could manually set up all the new attributes on the Magento admin.

**Comment by wagnert** [comment]
@ha0rex Hi, the creation of categories on-the-fly will be part of 3.8.0 that'll be released soon. Regard the attribute creation, I've got a question: As the CSV file for the products doesn't contain all the necessary information to create a new attributee, e. g. at least which type the attribute (text, text area, select, multi-select, etc.) should have, what will be your favorite solution to apply the missing information or where and when should we load it when we create the attributes?

**Comment by wagnert** [comment]
This feature has been released with version [3.8.0](https://github.com/techdivision/import-cli-simple/releases/tag/3.8.0).
