### ISSUE TITLE
Wrong Folder permission after failure 

### ISSUE THREAD

**Issue by larsroettig** [techdivision/import#148]
### Preconditions (*)
1. Magento 2.2
2. techdivision/import: **6.0.1**

### Steps to reproduce (*)
1. Run an failed Import wron csv format 

### Expected result (*)
```
drwxrwxrwx+ 2 www-data www-data 4096 May 21 23:11 df79607b-9be8-4f7b-9e20-b68768b50002
```

### Actual result (*)
```
drwx------+ 2 www-data www-data 4096 May 21 13:53 df79607b-9be8-4f7b-9e20-b68768b50002
```

**Comment by wagnert** [comment]
Hi @larsroettig, in general, this is an operating system task and can be configured e. g. with a user-specific [umask](https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html). 

Thanks for reporting
