### ISSUE TITLE
Additional Attributes Column

### ISSUE THREAD

**Issue by danrcoull** [techdivision/import#160]
Hi If the additional attributes column has html with inline css in it it has a tendancy to fail due to the ="" it explodes here and fails, but even with the \\ escape before the = it doesnt actually do anything different. 

Any solution ? 

Also   Found invalid entity type code "catalog_product" in file media.csv when trying to use a standard magento 2 csv base_image, small_image and thumbnail therefore never actually import.

**Comment by wagnert** [comment]
@danrcoull Can you please add/upload an example of the CSV file here? If not possible, you may contact me on our [gitter](https://gitter.im/techdivision/m2if) channel and we can open a private chat.

**Comment by wagnert** [comment]
@danrcoull As you didn't upload a file or contact me on Gitter, i'll close that issue. Also, I think the first problem is related to some escaping problems. As there has been some confusion during the last weeks, I've added more [detailed documentation](https://docs.m2if.com/file-structure/product-import/additional-attributes) that'll help to solve the problems.

Feel free to re-open the issue if you'll find the time to upload an example file that allows me to reproduce the issues with the `media.csv`.
