### ISSUE TITLE
Is it possible to use import without csv files?

### ISSUE THREAD

**Issue by serik303** [techdivision/import#164]
Hi, there!
i have one question, is it possible to use m2if programmatically? without CSV filels?
as an example magmi:

```
$dp = Magmi_DataPumpFactory::getDataPumpInstance("productimport");
$dp->beginImportSession("default", "create", new TestLogger());

$product = array(
 "name"=>"value",
....
 );
$dp->ingest($product);
$dp->endImportSession();
```
Tim, i know u can help me :)

Wbr, Sergej

**Comment by wagnert** [comment]
@serik303 Hm, for sure it is ;-) You can replace the CSV adapter with whatever you want. There is no documentation, but if you explain me what to do and give me some example data, I can guide you through the implementation :)

**Comment by serik303** [comment]
Tim, you are the best :)
example is very simple, i have, for example, one row from csv as array:
```
$attribute_set_to_import = (
        "attribute_set_name" => "Bag",
        "based_on" => "Default",
        "entity_type_code" => "catalog_product"
...
u s w
...
```
);
how can I import $attribute_set_to_import without saving an csv file?

thanks you

**Comment by serik303** [comment]
can you pls label issue as a question?

**Comment by wagnert** [comment]
Hi @serik303, done. As I’m not in office today, please give me a couple of times to investigate into that topic 🙂

**Comment by serik303** [comment]
it's ok :)

a little bit more what i mean: possibility to use import from external script like:
```
<?php
include(some/magic/m2if-php-file);
$attribute_set = an multidimensional array with attribute set(s) based on CSV File Structure 
$categories = an multidimensional array with categories based on CSV File Structure
... etc. for all core components

```
then something like

```$import_result = m2if_import($some_array, "command", "operation", "some_other_options");```

where
"command" is categories, attributes, products etc.,
"operation" is one from add-update, replace and delete,
"some_other_options" - maybe something what i don't know yet :)

**Comment by wagnert** [comment]
@serik303 Good morning. I have been thinking about your question. Can you give me a little bit more context about what you plan to do? What you wrote about is something like a function wrapper around the import command, right? Where do you plan to integrate it and what is the reason why you want to do it this way?

**Comment by serik303** [comment]
Moin, Tim!

Plan? It's simple - import/save my products, but why this way?
Because I save it single, one by one, most of the time one configurable + a couple of simple products at a time, but this applies not only to products: attribute set, attributes with values and categories too... single for each product.

Way how I can do it now, is to save csv files each for attribute set, attributes, categories and products and import it one by one. It’s better to be able to do it "on the fly" without saving the scv files.

Yes, i can do it other ways, bootstrap magento app, or use rest/soap api, but this is not my way :)

**Comment by wagnert** [comment]
Ok, understand so far :) But where did you get the data - in your case the array from? A webservice?

**Comment by serik303** [comment]
I parse html file from supplier to this array

**Comment by wagnert** [comment]
Ok, I would recommend to switch to the Gitter chat, what do you think?

**Comment by serik303** [comment]
ja, chat ist besser
habe noch niemals Gitter chat benutz, aber habe schon installiert

**Comment by wagnert** [comment]
Dann schreib mich mal kurz in einem privaten Chat an, dann können wir das detaillierter diskutieren :)

**Comment by wagnert** [comment]
@serik303 I'll close this issue in favor of https://github.com/techdivision/import-cli-simple/issues/236.

**Comment by wagnert** [comment]
techdivision/import-cli-simple#236
