### ISSUE TITLE
Use the import in Magento 2 module

### ISSUE THREAD

**Issue by vpashovski** [techdivision/import#171]
Hello,
it will be nice if there is a way to use the import module in custom Magento 2 module.

For example let's have this scenario.
There is 3rd party ERP system that provides products, images, categories with REST API.
I've build Magento 2 module that reads the data and transform it in an array.

When we have Array with product data I want to use some Import Adapter from this module and run something like that `$this->m2ifImport->import($array)`

Thanks :)

**Comment by wagnert** [comment]
@vpashovski Actually this is not possible. But we think about making it possible up from the next major version.

**Comment by vpashovski** [comment]
@wagnert Thanks!
Is there any timeline when we can expect next major version?

**Comment by wagnert** [comment]
As this will mean a switch from Symfony Console to Magento Framework instead, you can imagine that this will have a huge impact on M2IF. In general we plan to release a new major version with the next Magento minor version, which will be Magento 2.4. As there is no official release date for Magento 2.4, I can not give you an estimation when we'll release M2IF 4.x, I'm really sorry for that :-(

**Comment by vpashovski** [comment]
@wagnert Thanks for the answer :) Looking forward for this improvement :)
