### ISSUE TITLE
Disable the stock observer on the fly if there are no columns defined that are related to stock.

### ISSUE THREAD

**Issue by uroszunko** [techdivision/import#184]
- The stock quantities get overridden with 0 if there is no stock quantity column defined.

**Comment by HarmonyR** [comment]
Is there a work-around to disable stock updates?

**Comment by wagnert** [comment]
@HarmonyR You may remove the corresponding observer as well as the MSI import from the configuration. To do this, create a snippted `app/etc/configuration/operations.json` with the following content
```json
{
  "operations": {
    "ce": {
      "catalog_product": {
        "add-update": {
          "plugins": {
            "subject": {
              "id": "import.plugin.subject",
              "subjects": [
                {
                  "id": "import_product.subject.bunch",
                  "file-resolver": {
                    "prefix": "product-import"
                  },
                  "params": {
                    "copy-images": false,
                    "media-directory" : "pub/media/catalog/product",
                    "images-file-directory" : "var/importexport/media/catalog/product",
                    "clean-up-media-gallery": true,
                    "clean-up-empty-image-columns": true,
                    "clean-up-website-product-relations": true,
                    "clean-up-category-product-relations": true,
                    "clean-up-empty-columns": [
                      "special_price",
                      "special_price_from_date",
                      "special_price_to_date"
                    ]
                  },
                  "observers": [
                    {
                      "import": [
                        "import.observer.attribute.set",
                        "import.observer.additional.attribute",
                        "import_product.observer.url.key",
                        "import_product.observer.file.upload",
                        "import_product.observer.quality.and.stock.status",
                        "import_product.observer.product",
                        "import_product.observer.product.website.update",
                        "import_product.observer.category.product.update",
                        "import_product.observer.product.inventory.update",
                        "import_product.observer.product.attribute.update",
                        "import_product_url_rewrite.observer.product.url.rewrite",
                        "import_product_variant.observer.product.variant",
                        "import_product_bundle.observer.product.bundle",
                        "import_product_media.observer.product.media",
                        "import_product_media.observer.clean.up.media.gallery",
                        "import_product_link.observer.product.link",
                        "import_product_grouped.observer.product.grouped",
                        "import_product_msi.observer.product.source.item",
                        "import_product.observer.clean.up"
                      ]
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    }
  }
}
```
To remove the inventory update, remove the observers `"import_product.observer.product.inventory.update"` and `"import_product_msi.observer.product.source.item"` from the list. This should do the trick.

**Comment by HarmonyR** [comment]
@wagnert Would it also work if I copy vendor/techdivision/import-product/etc/configuration/shortcuts.json to app/etc/configuration/shortcuts.json and remove and the following?

- Line 54 "general/catalog_product/replace.msi",
- Line 78 "general/catalog_product/add-update.msi",

I have tested this and it appears to work, but I am not sure the implications. Maybe it's working by luck? I have attached the artifacts from a test run. Although it shows inventory-msi_20200616-000000_02.csv was created, it does not show it was imported.

[7350537b-9205-48bf-90a8-c757d348d9f2.zip](https://github.com/techdivision/import/files/4810293/7350537b-9205-48bf-90a8-c757d348d9f2.zip)
Please delete this zip after you download it.

**Comment by wagnert** [comment]
@HarmonyR Hm, I think in that case the legacy inventory should be updated, because of the `"import_product.observer.product.inventory.update"` update observer that has not been removed from the operation. The creation of the `inventory-msi_xxxx.csv` shouldn't be a problem, because it will not be processed as you've removed the appropriate operations.

**Comment by wagnert** [comment]
@uroszunko Up with version 3.8.22 it's possible to have the column empty or not available in the CSV file and the qty will not be touched.
