### ISSUE TITLE
Call to undefined method TechDivision\Import\Product\UrlRewrite\Services\ProductUrlRewriteProcessor::removeUrlRewrite()

### ISSUE THREAD

**Issue by HarmonyR** [techdivision/import#185]
**Issue**
When running the product import I am receiving the following error message. I am importing one product that already exists in Magento.

`PHP Fatal error:  Uncaught Error: Call to undefined method TechDivision\Import\Product\UrlRewrite\Services\ProductUrlRewriteProcessor::removeUrlRewrite() in vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteUpdateObserver.php:373
Stack trace:
#0 vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteUpdateObserver.php(148): TechDivision\Import\Product\UrlRewrite\Observers\UrlRewriteUpdateObserver->deleteUrlRewrite(Array)
#1 vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteObserver.php(253): TechDivision\Import\Product\UrlRewrite\Observers\UrlRewriteUpdateObserver->process()
#2 vendor/techdivision/import/src/Subjects/AbstractSubject.php(1005): TechDivision\Import\Product\UrlRewrite\Observers\UrlRewriteObserver->handle(Object(TechDivision\ in vendor/techdivision/import-product-url-rewrite/src/Observers/UrlRewriteUpdateObserver.php on line 373`
[m2if_3.8.20_error.zip](https://github.com/techdivision/import/files/4754410/m2if_3.8.20_error.zip)

**Environment**
- Magento CE 2.3.3
- PHP 7.3
- techdivision/import-cli-simple 3.8.20

**Steps To Reproduce**
1. Unzip attached files in Magento root (configurations and product data).
2. Run `vendor/bin/import-simple import:create:ok-file && vendor/bin/import-simple import:products`.
3. Possibly have to import a second time if the issue only happens when the product already exists in Magento.

**Comment by HarmonyR** [comment]
Here is the system.log from the product import attempt, in case it is helpful.
[system.log](https://github.com/techdivision/import/files/4754466/system.log)

**Comment by wagnert** [comment]
Hi @HarmonyR if you want to test you can use the 'techdivision/import-cli-simple` 3.8.x branch, manually update `techdivision/import-product-url-rewrite` to version `22.0.2` (change in `composer.json` and run `composer update`) or wait till I've release `techdivision/import-cli-simple` 3.8.21 tomorrow :-) Thanks for reporting that issue!!!
