### ISSUE TITLE
GLOB_BRACE is not available on Alpine Linux

### ISSUE THREAD

**Issue by amenk** [techdivision/import#189]
We are running some system on the official PHP docker container which is based on Alpine linux

Running M2IF results in an error

    PHP Warning:  Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in [/var/www/vendor/techdivision/import/src/Adapter/PhpFilesystemAdapter.php](https://github.com/techdivision/import/blob/16.x/src/Adapter/PhpFilesystemAdapter.php#L161) on line 161  

Magento's Alure Version had similar problems and can be [upgraded / patched](https://github.com/magento/magento2/issues/24635#issuecomment-546790701) 

The code looks like this:

            $dirs = $this->glob(dirname($pattern). DIRECTORY_SEPARATOR . '*', GLOB_ONLYDIR|GLOB_NOSORT|GLOB_BRACE);

I am wondering if GLOB_BRACE is even actively used? Just removing it kind of fixed the issues for us (sideffects not yet tested).

**Comment by amenk** [comment]
@wagnert Do we need this functionality here?

> GLOB_BRACE - Expands {a,b,c} to match 'a', 'b', or 'c'

**Comment by amenk** [comment]
The interesting part is, that GLOB_BRACE is used all over the place in Magento 2.3.4, wondering why no-one noticed before. See also https://github.com/magento/magento2/issues/24635#issuecomment-664913580

The most reasonable solution might be to switch our docker images to Debian, instead of Alpine.

**Comment by amenk** [comment]
I would say we won't fix that -- just use Debian based PHP images :)

**Comment by wagnert** [comment]
Ok, thanks for closing it :-)

**Comment by hardyjohnson** [comment]
@amenk the Magento Framework Glob class extends Laminas\Stdlib\Glob which tests whether GLOB_BRACE exists and uses a fallback if it doesn't. Alpine seems to run Magento just fine unless there are dependencies which don't explicitly use a Glob implementation which falls back when GLOB_BRACE is not defined. 

> The interesting part is, that GLOB_BRACE is used all over the place in Magento 2.3.4, wondering why no-one noticed before. See also [magento/magento2#24635 (comment)](https://github.com/magento/magento2/issues/24635#issuecomment-664913580)
> 
> The most reasonable solution might be to switch our docker images to Debian, instead of Alpine.
