### ISSUE TITLE
"Integrity constraint violation: 1048 Column 'entity_id' cannot be null" while importing products

### ISSUE THREAD

**Issue by niclashoyer** [techdivision/import#194]
I get the following error messages while importing simple products:

```
PHP Warning:  implode(): Invalid arguments passed in phar:///var/www/magento2/bin/import-cli-simple.phar/vendor/techdivision/import-category/src/Listeners/SortCategoryListener.php on line 159                                                                                                                                   
PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in phar:///var/www/magento2/bin/import-cli-simple.phar/vendor/techdivision/import-category/src/Listeners/SortCategoryListener.php on line 248
[...]
PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in phar:///var/www/magento2/bin/import-cli-simple.phar/vendor/techdivis
ion/import-category/src/Listeners/SortCategoryListener.php on line 267
 SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'entity_id' cannot be null when executing SQL "INSERT                                              
               INTO catalog_category_entity_int                                                                   
                    (entity_id,                                                                                                                                  
                     attribute_id,                                                                                
                     store_id,                                                                                                                                   
                     value)                                                                                       
             VALUES (,                                                                                                                                           
                     46,                                                                                          
                     0,                                                                                                                                          
                     1)" in file category-create_20200828-110655_01.csv on line 2                                 
```

Any hints on how to debug this one? I'm a bit lost here, since the categories where also imported correctly, but I don't know why the entity_id is missing in the query.

**Comment by wagnert** [comment]
Hi @niclashoyer, is it possible that you provide the file with the products?

**Comment by niclashoyer** [comment]
Unfortunately the file is too big to share, I'll try to find a canonical example.

**Comment by niclashoyer** [comment]
I found a minimal example just containing one line, I'll send it to you via email

**Comment by niclashoyer** [comment]
Oh, further inspection may solve this already: the column for the categories just had `/` in it, so just the seperator. This might trigger unexpected behavior on import. Removing this resolves this error (I get other SQL errors for duplicate entries in `cataloginventory_stock_item` but that may not be related to this)

**Comment by denvit** [comment]
@niclashoyer did you solved this issue with `cataloginventory_stock_item` as I'm having the same error?

**Comment by wagnert** [comment]
@denvit + @niclashoyer I've another customer who faced this problem today (I think it's the same one). He send me the CSV file so hopefully I'll be able to reproduce the issue. I'll check it today or tomorrow and come back to you :)

**Comment by denvit** [comment]
@wagnert I'm debugging right now and will let you know on Slack if I've found out something that could help you.

**Comment by wagnert** [comment]
Hi @niclashoyer, sorry for answering late. I had a look at your file and the `categories` column contains a simple `/`, which leads to the problem I think. If you want to use a value - you can also leave it empty for sure, you have to specify the name of the root category, e. g. `Default Category`. Hope that helps :)

**Comment by niclashoyer** [comment]
yes, removing the `/` fixed it, thanks. A better errors message would be cool.
