### ISSUE TITLE
Attribute visual swatch unable to render properly

### ISSUE THREAD

**Issue by MihaiComan90** [techdivision/import#200]
Following the guidelines from here:
> https://github.com/techdivision/import-sample-data/blob/4.x/generic/data/attributes/add-update-examples/attribute-import_20190103-180312_01.csv

There's an issue with rendering swatches, in the sense that if in the frontend_input column the value is "select" and the attribute_option_swatch is properly populated along with additional_data as a swatch type 2 ( which is visual ), the attribute is still being rendered in the frontend as a dropdown instead of a visual swatch. This is happening because the value of the frontend_input should be allowed to be swatch_visual instead of dropdown.

Magento Version: 2.4.1 / 2.4
name : techdivision/import-cli-simple
descrip. : CLI providing single-threaded Magento 2 importing functionality based on Pacemaker
keywords :
versions : * 3.8.33
type : library
license : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
names : techdivision/import-cli-simple

**Comment by pathmissing** [comment]
Thank you for reporting this issue, we will have a lookt at it.

**Comment by kenza-ya** [comment]
The problem has been fixed on 4.0
