### ISSUE TITLE
url_rewrite key constraint violation when the database has old rewrites

### ISSUE THREAD

**Issue by amenk** [techdivision/import#223]
**Describe the bug**

If there are old rewrites, the import might fail.

**To Reproduce**
1. Have a url_rewrite "example" in the database, of a product which no longer exists, rewrite type = 0
2. Import product with the same name
3. You might get an error

#

	Next TechDivision\Import\Exceptions\WrappedColumnException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'produkte/example.html-11' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID' when executing SQL "INSERT
		       INTO url_rewrite
		            (entity_type,
		             entity_id,
		             request_path,
		             target_path,
		             redirect_type,
		             store_id,
		             description,
		             is_autogenerated,
		             metadata)
		     VALUES (category,
		             967,
		             produkte/example.html,
		             catalog/category/view/id/967,
		             0,
		             11,
		             ,
		             1,
		             )" in file category-create_20210825_1.csv on line 3117 in /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import/src/Subjects/AbstractSubject.php:1461
	Stack trace:
	#0 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import/src/Subjects/AbstractSubject.php(973): TechDivision\Import\Subjects\AbstractSubject->wrapException(Array, Object(PDOException))
	#1 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import/src/Subjects/SubjectExecutor.php(131): TechDivision\Import\Subjects\AbstractSubject->import('bcc42b1f-cccc-4...', 'var/importexpor...')
	#2 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(168): TechDivision\Import\Subjects\SubjectExecutor->execute(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject), Array, 'bcc42b1f-cccc-4...', 'var/importexpor...')
	#3 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(120): TechDivision\Import\Plugins\SubjectPlugin->processSubject(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject))
	#4 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import/src/Plugins/PluginExecutor.php(117): TechDivision\Import\Plugins\SubjectPlugin->process()
	#5 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import/src/Modules/PluginModule.php(144): TechDivision\Import\Plugins\PluginExecutor->execute(Object(TechDivision\Import\Configuration\Jms\Configuration\Plugin))
	#6 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import-app-simple/src/Simple.php(622): TechDivision\Import\Modules\PluginModule->process()
	#7 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import-cli/src/Command/AbstractImportCommand.php(116): TechDivision\Import\App\Simple->process('bcc42b1f-cccc-4...')
	#8 /var/www/html/shop.example.com.staging.imi.de/web/vendor/symfony/console/Command/Command.php(255): TechDivision\Import\Cli\Command\AbstractImportCommand->execute(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#9 /var/www/html/shop.example.com.staging.imi.de/web/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#10 /var/www/html/shop.example.com.staging.imi.de/web/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(TechDivision\Import\Cli\Command\ImportCategoriesCommand), Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#11 /var/www/html/shop.example.com.staging.imi.de/web/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#12 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import-cli-simple/bootstrap.php(53): Symfony\Component\Console\Application->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#13 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import-cli-simple/bin/pacemaker.php(54): require('/var/www/html/s...')
	#14 /var/www/html/shop.example.com.staging.imi.de/web/vendor/techdivision/import-cli-simple/bin/import-simple(2): require('/var/www/html/s...')
	#15 {main}

**Expected behavior**
No error should appear. Maybe a new URL key should be generated.
Or this is a won't fix and the workarkound (below) is to be applied.
I am not sure if the URL keys are leftovers of a delete-import, so actually the issue (if any) might be in the delete job.

** Version Info **

	$ composer show techdivision/*
	techdivision/import                             dev-master 3002727
	techdivision/import-app-simple                  dev-master ff102a0
	techdivision/import-attribute                   dev-master 48d1f13
	techdivision/import-attribute-set               dev-master 7fc309a
	techdivision/import-cache                       dev-master 2ad65f8
	techdivision/import-cache-collection            dev-master 0e9f9c5
	techdivision/import-category                    dev-master 9207358
	techdivision/import-category-ee                 dev-master 90f3efb
	techdivision/import-cli                         dev-master 3262e99
	techdivision/import-cli-simple                  4.0.0-alpha9      
	techdivision/import-configuration               dev-master b28d114
	techdivision/import-configuration-jms           dev-master 6bd1de4
	techdivision/import-converter                   dev-master 0e78fd7
	techdivision/import-converter-ee                dev-master 947dfe9
	techdivision/import-converter-product-attribute dev-master 22c46b7
	techdivision/import-converter-product-category  dev-master 23c616f
	techdivision/import-customer                    dev-master ff9aab4
	techdivision/import-customer-address            dev-master 38c8f42
	techdivision/import-dbal                        dev-master eaf7a3c
	techdivision/import-dbal-collection             dev-master 0165c12
	techdivision/import-ee                          dev-master 5402a22
	techdivision/import-product                     dev-master fb9441f
	techdivision/import-product-bundle              dev-master fb81e91
	techdivision/import-product-bundle-ee           dev-master 1becedf
	techdivision/import-product-ee                  dev-master 65971a7
	techdivision/import-product-grouped             dev-master 0d986da
	techdivision/import-product-grouped-ee          dev-master 0dc2c86
	techdivision/import-product-link                dev-master aa7b39d
	techdivision/import-product-link-ee             dev-master 18f5da3
	techdivision/import-product-media               dev-master 1788e34
	techdivision/import-product-media-ee            dev-master a3600c7
	techdivision/import-product-msi                 dev-master 4120443
	techdivision/import-product-tier-price          dev-master 2f990dc
	techdivision/import-product-url-rewrite         dev-master 23ad32c
	techdivision/import-product-variant             dev-master 4bb06c0
	techdivision/import-product-variant-ee          dev-master b1a7354
	techdivision/import-serializer                  dev-master 995e519
	techdivision/import-serializer-csv              dev-master 9f0a428

Magento 2.3.4-p2
**Additional context**

** Possible Workarkound **

Something like this might help:

	> delete from url_rewrite where entity_type = 'category' and redirect_type = 0 AND entity_id not in (SELECT entity_id FROM catalog_category_entity)
	    -> ;
	Query OK, 806 rows affected, 1 warning (0.12 sec)

But could lead to new errors, for example on product import.

**Comment by wagnert** [comment]
Hi @amenk, I think we would need something like a reorganization of the URL rewrites that exactly executes the SQL statement you defined above. For example an additional command that runs the reorganization like `vendor/bin/import-cli-simple import:products:url:reorg` . Does that make sense for you?

**Comment by amenk** [comment]
@wagnert The problem is a bit that I do not know were the orphan rewrites come from. It might be due to past deletes via Pacemaker, in this case, would the URL rewrites be deleted as well? We have a custom job here, and might be missing the delete-rewrite-flag

**Comment by wagnert** [comment]
@amenk I think neither Pacemaker during product deletion nor deleting a product in the Magento Admin will delete the URL rewrites. I do not validate this, but this may be the origin of your problem.

**Comment by amenk** [comment]
Hm okay, we should validate that :)

**Comment by kenza-ya** [comment]
After testing, it has been fixed on 4.0.0 version already.

The two cleanups observers were built to fix this problem
`"import_category.observer.clear.url.rewrite"`
`"import_product_url_rewrite.observer.clear.url.rewrite"`
